# Site settings
title: No Divide Docs
email: matt@nodividestudio.com
description: > #
  Documentation for No Divide Studio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

exclude: [vendor]

# Build settings
markdown: kramdown

collections:
  boilerplate-docs:
    title: Boilerplate Docs
    output: true
