# Site settings
title: Documentation
email: matt@nodividestudio.com
description: > #
  Documentation for No Divide Studio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Excluse the vendor folder
exclude: [vendor]

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# Documentation Sections
collections:
  getting-started:
    title: Getting Started
    output: true
    permalink: /getting-started/:path/
